#!/usr/bin/env bash
# Sync the canonical Citrate contract-address table from citrate-chain
# into this repo's committed vendored copy at
# `gateway/src/generated/addresses.json`.
#
# Source-of-truth lives at:
#   citrate-chain/contracts/addresses/40204.json
# regenerated by:
#   citrate-chain/scripts/ops/emit-address-table.sh (after every
#   post-redeploy ceremony).
#
# Usage:
#   bash scripts/sync-addresses.sh           — overwrite the vendored copy
#   bash scripts/sync-addresses.sh --check   — CI gate (exit 1 on drift)
#
# Requires: jq.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CANONICAL="$(cd "${REPO_ROOT}/.." && pwd)/citrate-chain/contracts/addresses/40204.json"
VENDORED="${REPO_ROOT}/crates/chainio/src/generated/addresses.json"

CHECK_MODE=0
[[ "${1:-}" == "--check" ]] && CHECK_MODE=1

err() { echo "[sync-addresses] ERROR: $*" >&2; }
log() { echo "[sync-addresses] $*"; }

command -v jq >/dev/null || { err "jq is required"; exit 1; }

if [[ ! -f "$CANONICAL" ]]; then
  err "canonical not found at $CANONICAL"
  err "  Make sure citrate-chain is a sibling of this repo under Citrate-Labs/."
  exit 1
fi

# Minimum-shape gate. A malformed canonical must NOT pollute the vendored copy.
chain_id=$(jq -r '.chainId // empty' "$CANONICAL")
if [[ "$chain_id" != "40204" ]]; then
  err "canonical chainId is '$chain_id', expected 40204"
  exit 1
fi
for key in contracts aaStack; do
  if ! jq -e --arg k "$key" 'has($k)' "$CANONICAL" >/dev/null; then
    err "canonical missing required key: $key"; exit 1
  fi
done

# Normalize to stable JSON (sorted keys, 2-space indent, trailing newline).
NORMALIZED=$(jq --sort-keys '.' "$CANONICAL")

if [[ $CHECK_MODE -eq 1 ]]; then
  if [[ ! -f "$VENDORED" ]]; then
    err "no vendored copy at $VENDORED"; exit 1
  fi
  if ! diff -q <(printf '%s\n' "$NORMALIZED") "$VENDORED" >/dev/null; then
    err "vendored copy is OUT OF SYNC with canonical."
    err "  Run: bash scripts/sync-addresses.sh"
    err "  Then commit the diff."
    exit 1
  fi
  log "vendored copy matches canonical ✓"
  exit 0
fi

mkdir -p "$(dirname "$VENDORED")"
printf '%s\n' "$NORMALIZED" > "$VENDORED"
contracts=$(jq -r '.contracts | length' "$VENDORED")
aa=$(jq -r '.aaStack | length' "$VENDORED")
log "wrote $VENDORED"
log "  contracts: $contracts, aaStack: $aa"
